#!/bin/bash
# Helper scripts for Log Aggregator

echo "=== Log Aggregator Helper Scripts ==="
echo ""
echo "Available commands:"
echo ""
echo "  Start all services:"
echo "    docker compose up --build"
echo ""
echo "  Start in background:"
echo "    docker compose up --build -d"
echo ""
echo "  Run publisher (event simulator):"
echo "    docker compose --profile publisher up publisher"
echo ""
echo "  Run with multiple workers:"
echo "    docker compose --profile workers up -d"
echo ""
echo "  View logs:"
echo "    docker compose logs -f aggregator"
echo ""
echo "  Stop all:"
echo "    docker compose down"
echo ""
echo "  Stop and remove volumes (reset data):"
echo "    docker compose down -v"
echo ""
echo "  Check stats:"
echo "    curl http://localhost:8080/stats"
echo ""
echo "  Run tests:"
echo "    pip install -r tests/requirements.txt"
echo "    pytest tests/test_aggregator.py -v"
echo ""
echo "  Run K6 load test:"
echo "    k6 run k6/load_test.js"
echo ""
